/*
  PD_FOOD - Script de criação de banco (Firebird 3.0)
  Este script cria o banco de dados e toda a estrutura conforme o diagrama:
  CADGRUPOPRODUTO, CADPRODUTO, VENDA, VENDAITEM, VENDARCEITA, VENDADESCONTO.

  Observação: Firebird não possui "IF NOT EXISTS" para CREATE DATABASE.
  Execute a instrução de criação apenas em ambientes onde o arquivo não exista.
*/

/* 1) Criar o banco de dados (ajuste o caminho conforme necessário) */
/* Descomente a linha abaixo para criar o banco se ainda não existir. */
 CREATE DATABASE 'e:\Linx\PD_FOOD\database\pd_food.fdb' USER 'SYSDBA' PASSWORD 'masterkey' DEFAULT CHARACTER SET WIN1252;

/* 2) Sequences (autoincremento para chaves primárias) */
CREATE SEQUENCE GEN_CADGRUPOPRODUTO;
CREATE SEQUENCE GEN_CADPRODUTO;
CREATE SEQUENCE GEN_VENDA;
CREATE SEQUENCE GEN_VENDAITEM;
CREATE SEQUENCE GEN_VENDARCEITA;
CREATE SEQUENCE GEN_VENDADESCONTO;

/* 3) Tabelas */

/*
  CADGRUPOPRODUTO: grupos de produtos.
  - CODIGO: PK
  - DESCRICAO: descrição do grupo
*/
CREATE TABLE CADGRUPOPRODUTO (
  CODIGO INTEGER NOT NULL,
  DESCRICAO VARCHAR(40) NOT NULL,
  CONSTRAINT PK_CADGRUPOPRODUTO PRIMARY KEY (CODIGO)
);

/*
  CADPRODUTO: catálogo de produtos.
  - CODIGO: PK
  - DESCRICAO: nome do produto
  - CODIGO_GRUPO: FK para CADGRUPOPRODUTO(CODIGO)
  - VALOR: preço unitário
*/
CREATE TABLE CADPRODUTO (
  CODIGO INTEGER NOT NULL,
  DESCRICAO VARCHAR(40) NOT NULL,
  CODIGO_GRUPO INTEGER NOT NULL,
  VALOR NUMERIC(18,2) NOT NULL,
  CONSTRAINT PK_CADPRODUTO PRIMARY KEY (CODIGO),
  CONSTRAINT FK_CADPRODUTO_GRUPO FOREIGN KEY (CODIGO_GRUPO) REFERENCES CADGRUPOPRODUTO(CODIGO)
);

/*
  VENDA: cabeçalho da venda.
  - CODIGO: PK
  - DATA: data da venda
  - VALOR_BRUTO: soma dos itens
  - VALOR_DESCONTO: descontos aplicados
  - VALOR_LIQUIDO: total líquido
  - CANCELADA: indicador 'S'/'N'
*/
CREATE TABLE VENDA (
  CODIGO INTEGER NOT NULL,
  DATA DATE NOT NULL,
  VALOR_BRUTO NUMERIC(18,2) NOT NULL DEFAULT 0,
  VALOR_DESCONTO NUMERIC(18,2) NOT NULL DEFAULT 0,
  VALOR_LIQUIDO NUMERIC(18,2) NOT NULL DEFAULT 0,
  CANCELADA CHAR(1) NOT NULL DEFAULT 'N',
  CONSTRAINT PK_VENDA PRIMARY KEY (CODIGO),
  CONSTRAINT CHK_VENDA_CANCELADA CHECK (CANCELADA IN ('S','N'))
);

/*
  VENDAITEM: itens da venda.
  - CODIGO_SEQUENCIAL: PK (sequencial de item)
  - CODIGO_VENDA: FK para VENDA(CODIGO)
  - CODIGO_PRODUTO: FK para CADPRODUTO(CODIGO)
  - VALOR: preço unitário aplicado
  - QTD: quantidade
  - VALOR_SUBTOTAL: calculado por (VALOR * QTD)
*/
CREATE TABLE VENDAITEM (
  CODIGO_SEQUENCIAL INTEGER NOT NULL,
  CODIGO_VENDA INTEGER NOT NULL,
  CODIGO_PRODUTO INTEGER NOT NULL,
  VALOR NUMERIC(18,2) NOT NULL,
  QTD NUMERIC(18,3) NOT NULL,
  VALOR_SUBTOTAL NUMERIC(18,2) COMPUTED BY (VALOR * QTD),
  CONSTRAINT PK_VENDAITEM PRIMARY KEY (CODIGO_SEQUENCIAL),
  CONSTRAINT FK_VENDAITEM_VENDA FOREIGN KEY (CODIGO_VENDA) REFERENCES VENDA(CODIGO),
  CONSTRAINT FK_VENDAITEM_PROD FOREIGN KEY (CODIGO_PRODUTO) REFERENCES CADPRODUTO(CODIGO)
);

/*
  VENDARCEITA: receitas adicionais vinculadas à venda.
  - CODIGO_SEQUENCIAL: PK
  - CODIGO_VENDA: FK para VENDA(CODIGO)
  - CODIGO_RECEITA: código da receita (não há tabela de referência no diagrama)
  - DESCRICAO_RECEITA: descrição textual
  - VALOR: valor da receita
*/
CREATE TABLE VENDARCEITA (
  CODIGO_SEQUENCIAL INTEGER NOT NULL,
  CODIGO_VENDA INTEGER NOT NULL,
  CODIGO_RECEITA INTEGER NOT NULL,
  DESCRICAO_RECEITA VARCHAR(40) NOT NULL,
  VALOR NUMERIC(18,2) NOT NULL,
  CONSTRAINT PK_VENDARCEITA PRIMARY KEY (CODIGO_SEQUENCIAL),
  CONSTRAINT FK_VENDARCEITA_VENDA FOREIGN KEY (CODIGO_VENDA) REFERENCES VENDA(CODIGO)
);

/*
  VENDADESCONTO: descontos aplicados por venda.
  - CODIGO_SEQUENCIAL: PK
  - CODIGO_VENDA: FK para VENDA(CODIGO)
  - CODIGO_DESCONTO: código do desconto (não há tabela de referência no diagrama)
  - DESCRICAO_DESCONTO: descrição textual
  - VALOR_PERCENTUAL: percentual aplicado
*/
CREATE TABLE VENDADESCONTO (
  CODIGO_SEQUENCIAL INTEGER NOT NULL,
  CODIGO_VENDA INTEGER NOT NULL,
  CODIGO_DESCONTO INTEGER NOT NULL,
  DESCRICAO_DESCONTO VARCHAR(40) NOT NULL,
  VALOR_PERCENTUAL NUMERIC(5,2) NOT NULL,
  CONSTRAINT PK_VENDADESCONTO PRIMARY KEY (CODIGO_SEQUENCIAL),
  CONSTRAINT FK_VENDADESCONTO_VENDA FOREIGN KEY (CODIGO_VENDA) REFERENCES VENDA(CODIGO)
);

/* 4) Comentários explicativos */
COMMENT ON TABLE CADGRUPOPRODUTO IS 'Grupos de produtos';
COMMENT ON COLUMN CADGRUPOPRODUTO.CODIGO IS 'Chave primária do grupo';
COMMENT ON COLUMN CADGRUPOPRODUTO.DESCRICAO IS 'Descrição do grupo (até 40 caracteres)';

COMMENT ON TABLE CADPRODUTO IS 'Cadastro de produtos';
COMMENT ON COLUMN CADPRODUTO.CODIGO IS 'Chave primária do produto';
COMMENT ON COLUMN CADPRODUTO.DESCRICAO IS 'Nome/descrição do produto';
COMMENT ON COLUMN CADPRODUTO.CODIGO_GRUPO IS 'FK para CADGRUPOPRODUTO';
COMMENT ON COLUMN CADPRODUTO.VALOR IS 'Preço unitário';

COMMENT ON TABLE VENDA IS 'Cabeçalho da venda';
COMMENT ON COLUMN VENDA.CODIGO IS 'Chave primária da venda';
COMMENT ON COLUMN VENDA.DATA IS 'Data da venda';
COMMENT ON COLUMN VENDA.VALOR_BRUTO IS 'Soma dos itens';
COMMENT ON COLUMN VENDA.VALOR_DESCONTO IS 'Total de descontos';
COMMENT ON COLUMN VENDA.VALOR_LIQUIDO IS 'Total líquido';
COMMENT ON COLUMN VENDA.CANCELADA IS 'Indicador de cancelamento (S/N)';

COMMENT ON TABLE VENDAITEM IS 'Itens da venda';
COMMENT ON COLUMN VENDAITEM.CODIGO_SEQUENCIAL IS 'Sequencial do item (PK)';
COMMENT ON COLUMN VENDAITEM.CODIGO_VENDA IS 'FK para VENDA';
COMMENT ON COLUMN VENDAITEM.CODIGO_PRODUTO IS 'FK para CADPRODUTO';
COMMENT ON COLUMN VENDAITEM.VALOR IS 'Preço unitário aplicado no item';
COMMENT ON COLUMN VENDAITEM.QTD IS 'Quantidade do item';
COMMENT ON COLUMN VENDAITEM.VALOR_SUBTOTAL IS 'Subtotal calculado (VALOR * QTD)';

COMMENT ON TABLE VENDARCEITA IS 'Receitas associadas à venda';
COMMENT ON COLUMN VENDARCEITA.CODIGO_SEQUENCIAL IS 'Sequencial da receita (PK)';
COMMENT ON COLUMN VENDARCEITA.CODIGO_VENDA IS 'FK para VENDA';
COMMENT ON COLUMN VENDARCEITA.CODIGO_RECEITA IS 'Código da receita (não possui tabela no diagrama)';
COMMENT ON COLUMN VENDARCEITA.DESCRICAO_RECEITA IS 'Descrição da receita';
COMMENT ON COLUMN VENDARCEITA.VALOR IS 'Valor da receita';

COMMENT ON TABLE VENDADESCONTO IS 'Descontos associados à venda';
COMMENT ON COLUMN VENDADESCONTO.CODIGO_SEQUENCIAL IS 'Sequencial do desconto (PK)';
COMMENT ON COLUMN VENDADESCONTO.CODIGO_VENDA IS 'FK para VENDA';
COMMENT ON COLUMN VENDADESCONTO.CODIGO_DESCONTO IS 'Código do desconto (não possui tabela no diagrama)';
COMMENT ON COLUMN VENDADESCONTO.DESCRICAO_DESCONTO IS 'Descrição do desconto';
COMMENT ON COLUMN VENDADESCONTO.VALOR_PERCENTUAL IS 'Percentual aplicado';

/* 5) Triggers de autoincremento para PKs */
SET TERM ^ ;

CREATE TRIGGER BI_CADGRUPOPRODUTO FOR CADGRUPOPRODUTO ACTIVE BEFORE INSERT POSITION 0 AS
BEGIN
  IF (NEW.CODIGO IS NULL) THEN NEW.CODIGO = NEXT VALUE FOR GEN_CADGRUPOPRODUTO;
END ^

CREATE TRIGGER BI_CADPRODUTO FOR CADPRODUTO ACTIVE BEFORE INSERT POSITION 0 AS
BEGIN
  IF (NEW.CODIGO IS NULL) THEN NEW.CODIGO = NEXT VALUE FOR GEN_CADPRODUTO;
END ^

CREATE TRIGGER BI_VENDA FOR VENDA ACTIVE BEFORE INSERT POSITION 0 AS
BEGIN
  IF (NEW.CODIGO IS NULL) THEN NEW.CODIGO = NEXT VALUE FOR GEN_VENDA;
END ^

CREATE TRIGGER BI_VENDAITEM FOR VENDAITEM ACTIVE BEFORE INSERT POSITION 0 AS
BEGIN
  IF (NEW.CODIGO_SEQUENCIAL IS NULL) THEN NEW.CODIGO_SEQUENCIAL = NEXT VALUE FOR GEN_VENDAITEM;
END ^

CREATE TRIGGER BI_VENDARCEITA FOR VENDARCEITA ACTIVE BEFORE INSERT POSITION 0 AS
BEGIN
  IF (NEW.CODIGO_SEQUENCIAL IS NULL) THEN NEW.CODIGO_SEQUENCIAL = NEXT VALUE FOR GEN_VENDARCEITA;
END ^

CREATE TRIGGER BI_VENDADESCONTO FOR VENDADESCONTO ACTIVE BEFORE INSERT POSITION 0 AS
BEGIN
  IF (NEW.CODIGO_SEQUENCIAL IS NULL) THEN NEW.CODIGO_SEQUENCIAL = NEXT VALUE FOR GEN_VENDADESCONTO;
END ^

SET TERM ; ^

/* 6) Índices para consultas frequentes */
CREATE INDEX IDX_CADGRUPOPRODUTO_DESCRICAO ON CADGRUPOPRODUTO (DESCRICAO);
CREATE INDEX IDX_CADPRODUTO_DESCRICAO ON CADPRODUTO (DESCRICAO);
CREATE INDEX IDX_CADPRODUTO_GRUPO ON CADPRODUTO (CODIGO_GRUPO);
CREATE INDEX IDX_VENDA_DATA ON VENDA (DATA);
CREATE INDEX IDX_VENDAITEM_VENDA ON VENDAITEM (CODIGO_VENDA);
CREATE INDEX IDX_VENDAITEM_PRODUTO ON VENDAITEM (CODIGO_PRODUTO);
CREATE INDEX IDX_VENDARCEITA_VENDA ON VENDARCEITA (CODIGO_VENDA);
CREATE INDEX IDX_VENDADESCONTO_VENDA ON VENDADESCONTO (CODIGO_VENDA);

/* Fim do script de criação de estrutura */