/* Seed de dados iniciais */
INSERT INTO CADGRUPOPRODUTO (DESCRICAO) VALUES ('Lanches');
INSERT INTO CADGRUPOPRODUTO (DESCRICAO) VALUES ('Bebidas');
INSERT INTO CADGRUPOPRODUTO (DESCRICAO) VALUES ('Sobremesas');

INSERT INTO CADPRODUTO (DESCRICAO, CODIGO_GRUPO, VALOR) VALUES ('Hamburguer Clássico', 1, 19.90);
INSERT INTO CADPRODUTO (DESCRICAO, CODIGO_GRUPO, VALOR) VALUES ('Refrigerante Lata', 2, 6.00);
INSERT INTO CADPRODUTO (DESCRICAO, CODIGO_GRUPO, VALOR) VALUES ('Sorvete', 3, 12.00);

INSERT INTO VENDA (DATA, VALOR_BRUTO, VALOR_DESCONTO, VALOR_LIQUIDO, CANCELADA)
VALUES (CURRENT_DATE, 0, 0, 0, 'N');

INSERT INTO VENDAITEM (CODIGO_VENDA, CODIGO_PRODUTO, VALOR, QTD) VALUES (1, 1, 19.90, 1);
INSERT INTO VENDAITEM (CODIGO_VENDA, CODIGO_PRODUTO, VALOR, QTD) VALUES (1, 2, 6.00, 2);

INSERT INTO VENDARCEITA (CODIGO_VENDA, CODIGO_RECEITA, DESCRICAO_RECEITA, VALOR) VALUES (1, 1, 'Taxa de Serviço', 2.00);
INSERT INTO VENDADESCONTO (CODIGO_VENDA, CODIGO_DESCONTO, DESCRICAO_DESCONTO, VALOR_PERCENTUAL) VALUES (1, 1, 'Desconto Promocional', 10.00);